apiVersion: v1
kind: Service
metadata:
  name: microblog-mysql-service
  labels:
    app: microblog
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: microblog
    tier: mysql