apiVersion: v1
kind: Service
metadata:
  name: microblog-service
  labels:
    app: microblog
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31500
  selector:
        app: microblog
        tier: frontend
